project:
  type: default
  output-dir: quarto_outputs

format:
    html:
      self-contained: true
      toc: false
      code-copy: true
      code-overflow: wrap
      html-math-method: katex
      fig-width: 8
      mainfont: "Helvetica"

author: "Rafael J. Scholtz"
date: last-modified